--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Debian 16.4-1.pgdg120+1)
-- Dumped by pg_dump version 16.4 (Debian 16.4-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS social_novel;
--
-- Name: social_novel; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE social_novel WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE social_novel OWNER TO postgres;

\connect social_novel

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: character; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."character" (
    username character varying NOT NULL,
    name text NOT NULL
);


ALTER TABLE public."character" OWNER TO postgres;

--
-- Name: chat; Type: TABLE; Schema: public; Owner: writter
--

CREATE TABLE public.chat (
    id integer NOT NULL,
    content text,
    "from" character varying NOT NULL,
    "to" character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    image text
);


ALTER TABLE public.chat OWNER TO writter;

--
-- Name: post; Type: TABLE; Schema: public; Owner: writter
--

CREATE TABLE public.post (
    id integer NOT NULL,
    parent integer,
    content text DEFAULT ''::text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "character" character varying NOT NULL,
    reaction integer DEFAULT 0 NOT NULL,
    media text DEFAULT ''::text NOT NULL,
    feeling text DEFAULT ''::text NOT NULL,
    is_with text DEFAULT ''::text NOT NULL
);


ALTER TABLE public.post OWNER TO writter;

--
-- Name: post_id_seq; Type: SEQUENCE; Schema: public; Owner: writter
--

ALTER TABLE public.post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: character; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."character" (username, name) FROM stdin;
hehe	Hoho
admin	Admin
\.


--
-- Data for Name: chat; Type: TABLE DATA; Schema: public; Owner: writter
--

COPY public.chat (id, content, "from", "to", created_at, image) FROM stdin;
\.


--
-- Data for Name: post; Type: TABLE DATA; Schema: public; Owner: writter
--

COPY public.post (id, parent, content, created_at, "character", reaction, media, feeling, is_with) FROM stdin;
2	\N	hello	2024-09-12 11:19:40.690196	admin	0		fun	Haha
\.


--
-- Name: post_id_seq; Type: SEQUENCE SET; Schema: public; Owner: writter
--

SELECT pg_catalog.setval('public.post_id_seq', 2, true);


--
-- Name: chat chat_pk; Type: CONSTRAINT; Schema: public; Owner: writter
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT chat_pk PRIMARY KEY (id);


--
-- Name: post post_pk; Type: CONSTRAINT; Schema: public; Owner: writter
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT post_pk PRIMARY KEY (id);


--
-- Name: character user_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."character"
    ADD CONSTRAINT user_pk PRIMARY KEY (username);


--
-- Name: chat_id_uindex; Type: INDEX; Schema: public; Owner: writter
--

CREATE UNIQUE INDEX chat_id_uindex ON public.chat USING btree (id);


--
-- Name: chat chat_user_username_fk; Type: FK CONSTRAINT; Schema: public; Owner: writter
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT chat_user_username_fk FOREIGN KEY ("from") REFERENCES public."character"(username);


--
-- Name: chat chat_user_username_fk_2; Type: FK CONSTRAINT; Schema: public; Owner: writter
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT chat_user_username_fk_2 FOREIGN KEY ("to") REFERENCES public."character"(username);


--
-- Name: post post_post_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: writter
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT post_post_id_fk FOREIGN KEY (parent) REFERENCES public.post(id);


--
-- Name: post post_user_username_fk; Type: FK CONSTRAINT; Schema: public; Owner: writter
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT post_user_username_fk FOREIGN KEY ("character") REFERENCES public."character"(username);


--
-- Name: DATABASE social_novel; Type: ACL; Schema: -; Owner: postgres
--

GRANT ALL ON DATABASE social_novel TO writter;


--
-- PostgreSQL database dump complete
--

